title: Ben Sinclair
author: Ben Sinclair
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  The blog of Ben Sinclair
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Ben Sinclair
  tagline: CTO @ Tithe.ly
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: bensinclair
    github:  bensinclair
    linkedIn: in/benlsinclair
    rss: rss

# Build settings
remote_theme: plainwhite

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-feed
